
package br.com.fiap.sismultas.web.ws.autentica;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AutenticaService", targetNamespace = "http://ws.sismultas.fiap.com.br/", wsdlLocation = "http://localhost:8081/Autentica?wsdl")
public class AutenticaService
    extends Service
{

    private final static URL AUTENTICASERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.com.fiap.sismultas.web.ws.autentica.AutenticaService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.com.fiap.sismultas.web.ws.autentica.AutenticaService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8081/Autentica?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8081/Autentica?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        AUTENTICASERVICE_WSDL_LOCATION = url;
    }

    public AutenticaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AutenticaService() {
        super(AUTENTICASERVICE_WSDL_LOCATION, new QName("http://ws.sismultas.fiap.com.br/", "AutenticaService"));
    }

    /**
     * 
     * @return
     *     returns Autentica
     */
    @WebEndpoint(name = "AutenticaPort")
    public Autentica getAutenticaPort() {
        return super.getPort(new QName("http://ws.sismultas.fiap.com.br/", "AutenticaPort"), Autentica.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Autentica
     */
    @WebEndpoint(name = "AutenticaPort")
    public Autentica getAutenticaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.sismultas.fiap.com.br/", "AutenticaPort"), Autentica.class, features);
    }

}
