
package br.com.fiap.sismultas.web.ws.email;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "EnviaEmailNotificacao", targetNamespace = "http://ws.sismultas.fiap.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EnviaEmailNotificacao {


    /**
     * 
     * @param relatorio
     * @throws Exception_Exception
     */
    @WebMethod(action = "enviaEmailNotificacao")
    @RequestWrapper(localName = "enviaEmailNotificacao", targetNamespace = "http://ws.sismultas.fiap.com.br/", className = "br.com.fiap.sismultas.web.ws.email.EnviaEmailNotificacao_Type")
    @ResponseWrapper(localName = "enviaEmailNotificacaoResponse", targetNamespace = "http://ws.sismultas.fiap.com.br/", className = "br.com.fiap.sismultas.web.ws.email.EnviaEmailNotificacaoResponse")
    public void enviaEmailNotificacao(
        @WebParam(name = "relatorio", targetNamespace = "")
        RelatorioVO relatorio)
        throws Exception_Exception
    ;

}
