
package br.com.fiap.sismultas.mule.user.ws;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "UsuarioWSBean", targetNamespace = "http://ws.sismultas.fiap.com.br/")
public interface UsuarioWSBean {


    /**
     * 
     * @param arg0
     * @return
     *     returns br.com.fiap.sismultas.mule.user.ws.PessoaVO
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cadastra", targetNamespace = "http://ws.sismultas.fiap.com.br/", className = "br.com.fiap.sismultas.mule.user.ws.Cadastra")
    @ResponseWrapper(localName = "cadastraResponse", targetNamespace = "http://ws.sismultas.fiap.com.br/", className = "br.com.fiap.sismultas.mule.user.ws.CadastraResponse")
    public PessoaVO cadastra(
        @WebParam(name = "arg0", targetNamespace = "")
        PessoaVO arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<br.com.fiap.sismultas.mule.user.ws.PerfilVO>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPerfis", targetNamespace = "http://ws.sismultas.fiap.com.br/", className = "br.com.fiap.sismultas.mule.user.ws.GetPerfis")
    @ResponseWrapper(localName = "getPerfisResponse", targetNamespace = "http://ws.sismultas.fiap.com.br/", className = "br.com.fiap.sismultas.mule.user.ws.GetPerfisResponse")
    public List<PerfilVO> getPerfis()
        throws Exception_Exception
    ;

}
