
package br.com.fiap.sismultas.web.ws.usuario;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Usuario", targetNamespace = "http://ws.sismultas.fiap.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Usuario {


    /**
     * 
     * @param arg0
     * @return
     *     returns br.com.fiap.sismultas.web.ws.usuario.PessoaVO
     * @throws Exception_Exception
     */
    @WebMethod(action = "cadastra")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cadastra", targetNamespace = "http://ws.sismultas.fiap.com.br/", className = "br.com.fiap.sismultas.web.ws.usuario.Cadastra")
    @ResponseWrapper(localName = "cadastraResponse", targetNamespace = "http://ws.sismultas.fiap.com.br/", className = "br.com.fiap.sismultas.web.ws.usuario.CadastraResponse")
    public PessoaVO cadastra(
        @WebParam(name = "arg0", targetNamespace = "")
        PessoaVO arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<br.com.fiap.sismultas.web.ws.usuario.PerfilVO>
     * @throws Exception_Exception
     */
    @WebMethod(action = "getPerfis")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPerfis", targetNamespace = "http://ws.sismultas.fiap.com.br/", className = "br.com.fiap.sismultas.web.ws.usuario.GetPerfis")
    @ResponseWrapper(localName = "getPerfisResponse", targetNamespace = "http://ws.sismultas.fiap.com.br/", className = "br.com.fiap.sismultas.web.ws.usuario.GetPerfisResponse")
    public List<PerfilVO> getPerfis()
        throws Exception_Exception
    ;

}
