
package br.com.fiap.sismultas.mule.ws;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MultasWSBean", targetNamespace = "http://ws.sismultas.fiap.com.br/")
public interface MultasWSBean {


    /**
     * 
     * @param idInfracao
     * @return
     *     returns br.com.fiap.sismultas.mule.ws.IdOperacaoVO
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "emiteNotificacao", targetNamespace = "http://ws.sismultas.fiap.com.br/", className = "br.com.fiap.sismultas.mule.ws.EmiteNotificacao")
    @ResponseWrapper(localName = "emiteNotificacaoResponse", targetNamespace = "http://ws.sismultas.fiap.com.br/", className = "br.com.fiap.sismultas.mule.ws.EmiteNotificacaoResponse")
    public IdOperacaoVO emiteNotificacao(
        @WebParam(name = "idInfracao", targetNamespace = "")
        IdOperacaoVO idInfracao)
        throws Exception_Exception
    ;

    /**
     * 
     * @param relatorio
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "enviaEmailNotificacao", targetNamespace = "http://ws.sismultas.fiap.com.br/", className = "br.com.fiap.sismultas.mule.ws.EnviaEmailNotificacao")
    @ResponseWrapper(localName = "enviaEmailNotificacaoResponse", targetNamespace = "http://ws.sismultas.fiap.com.br/", className = "br.com.fiap.sismultas.mule.ws.EnviaEmailNotificacaoResponse")
    public void enviaEmailNotificacao(
        @WebParam(name = "relatorio", targetNamespace = "")
        RelatorioVO relatorio)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns br.com.fiap.sismultas.mule.ws.RelatorioVO
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "geraRelatorioMultas", targetNamespace = "http://ws.sismultas.fiap.com.br/", className = "br.com.fiap.sismultas.mule.ws.GeraRelatorioMultas")
    @ResponseWrapper(localName = "geraRelatorioMultasResponse", targetNamespace = "http://ws.sismultas.fiap.com.br/", className = "br.com.fiap.sismultas.mule.ws.GeraRelatorioMultasResponse")
    public RelatorioVO geraRelatorioMultas(
        @WebParam(name = "arg0", targetNamespace = "")
        MultaVO arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<br.com.fiap.sismultas.mule.ws.InfracaoVO>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMultas", targetNamespace = "http://ws.sismultas.fiap.com.br/", className = "br.com.fiap.sismultas.mule.ws.GetMultas")
    @ResponseWrapper(localName = "getMultasResponse", targetNamespace = "http://ws.sismultas.fiap.com.br/", className = "br.com.fiap.sismultas.mule.ws.GetMultasResponse")
    public List<InfracaoVO> getMultas(
        @WebParam(name = "arg0", targetNamespace = "")
        MultaVO arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param idNotificacao
     * @return
     *     returns br.com.fiap.sismultas.mule.ws.RelatorioVO
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "geraArquivoNotificacao", targetNamespace = "http://ws.sismultas.fiap.com.br/", className = "br.com.fiap.sismultas.mule.ws.GeraArquivoNotificacao")
    @ResponseWrapper(localName = "geraArquivoNotificacaoResponse", targetNamespace = "http://ws.sismultas.fiap.com.br/", className = "br.com.fiap.sismultas.mule.ws.GeraArquivoNotificacaoResponse")
    public RelatorioVO geraArquivoNotificacao(
        @WebParam(name = "idNotificacao", targetNamespace = "")
        IdOperacaoVO idNotificacao)
        throws Exception_Exception
    ;

    /**
     * 
     * @param dadosMulta
     * @return
     *     returns br.com.fiap.sismultas.mule.ws.IdOperacaoVO
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "processaDadosMulta", targetNamespace = "http://ws.sismultas.fiap.com.br/", className = "br.com.fiap.sismultas.mule.ws.ProcessaDadosMulta")
    @ResponseWrapper(localName = "processaDadosMultaResponse", targetNamespace = "http://ws.sismultas.fiap.com.br/", className = "br.com.fiap.sismultas.mule.ws.ProcessaDadosMultaResponse")
    public IdOperacaoVO processaDadosMulta(
        @WebParam(name = "dadosMulta", targetNamespace = "")
        MultaVO dadosMulta)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<br.com.fiap.sismultas.mule.ws.GravidadeInfracaoVO>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGravidades", targetNamespace = "http://ws.sismultas.fiap.com.br/", className = "br.com.fiap.sismultas.mule.ws.GetGravidades")
    @ResponseWrapper(localName = "getGravidadesResponse", targetNamespace = "http://ws.sismultas.fiap.com.br/", className = "br.com.fiap.sismultas.mule.ws.GetGravidadesResponse")
    public List<GravidadeInfracaoVO> getGravidades()
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns br.com.fiap.sismultas.mule.ws.ItemCTBVO
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cadastraItemCTB", targetNamespace = "http://ws.sismultas.fiap.com.br/", className = "br.com.fiap.sismultas.mule.ws.CadastraItemCTB")
    @ResponseWrapper(localName = "cadastraItemCTBResponse", targetNamespace = "http://ws.sismultas.fiap.com.br/", className = "br.com.fiap.sismultas.mule.ws.CadastraItemCTBResponse")
    public ItemCTBVO cadastraItemCTB(
        @WebParam(name = "arg0", targetNamespace = "")
        ItemCTBVO arg0)
        throws Exception_Exception
    ;

}
