
package br.com.fiap.sismultas.web.ws.veiculo;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "VeiculoService", targetNamespace = "http://ws.sismultas.fiap.com.br/", wsdlLocation = "http://localhost:8081/Veiculo?wsdl")
public class VeiculoService
    extends Service
{

    private final static URL VEICULOSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.com.fiap.sismultas.web.ws.veiculo.VeiculoService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.com.fiap.sismultas.web.ws.veiculo.VeiculoService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8081/Veiculo?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8081/Veiculo?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        VEICULOSERVICE_WSDL_LOCATION = url;
    }

    public VeiculoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VeiculoService() {
        super(VEICULOSERVICE_WSDL_LOCATION, new QName("http://ws.sismultas.fiap.com.br/", "VeiculoService"));
    }

    /**
     * 
     * @return
     *     returns Veiculo
     */
    @WebEndpoint(name = "VeiculoPort")
    public Veiculo getVeiculoPort() {
        return super.getPort(new QName("http://ws.sismultas.fiap.com.br/", "VeiculoPort"), Veiculo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Veiculo
     */
    @WebEndpoint(name = "VeiculoPort")
    public Veiculo getVeiculoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.sismultas.fiap.com.br/", "VeiculoPort"), Veiculo.class, features);
    }

}
