
package br.com.fiap.sismultas.web.ws.ctb;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Ctb", targetNamespace = "http://ws.sismultas.fiap.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Ctb {


    /**
     * 
     * @param arg0
     * @return
     *     returns br.com.fiap.sismultas.web.ws.ctb.ItemCTBVO
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cadastraItemCtb", targetNamespace = "http://ws.sismultas.fiap.com.br/", className = "br.com.fiap.sismultas.web.ws.ctb.CadastraItemCtb")
    @ResponseWrapper(localName = "cadastraItemCtbResponse", targetNamespace = "http://ws.sismultas.fiap.com.br/", className = "br.com.fiap.sismultas.web.ws.ctb.CadastraItemCtbResponse")
    public ItemCTBVO cadastraItemCtb(
        @WebParam(name = "arg0", targetNamespace = "")
        ItemCTBVO arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<br.com.fiap.sismultas.web.ws.ctb.GravidadeInfracaoVO>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGravidades", targetNamespace = "http://ws.sismultas.fiap.com.br/", className = "br.com.fiap.sismultas.web.ws.ctb.GetGravidades")
    @ResponseWrapper(localName = "getGravidadesResponse", targetNamespace = "http://ws.sismultas.fiap.com.br/", className = "br.com.fiap.sismultas.web.ws.ctb.GetGravidadesResponse")
    public List<GravidadeInfracaoVO> getGravidades()
        throws Exception_Exception
    ;

}
