
package br.com.fiap.sismultas.web.ws.ctb;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CtbService", targetNamespace = "http://ws.sismultas.fiap.com.br/", wsdlLocation = "http://localhost:8081/Ctb?wsdl")
public class CtbService
    extends Service
{

    private final static URL CTBSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.com.fiap.sismultas.web.ws.ctb.CtbService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.com.fiap.sismultas.web.ws.ctb.CtbService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8081/Ctb?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8081/Ctb?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CTBSERVICE_WSDL_LOCATION = url;
    }

    public CtbService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CtbService() {
        super(CTBSERVICE_WSDL_LOCATION, new QName("http://ws.sismultas.fiap.com.br/", "CtbService"));
    }

    /**
     * 
     * @return
     *     returns Ctb
     */
    @WebEndpoint(name = "CtbPort")
    public Ctb getCtbPort() {
        return super.getPort(new QName("http://ws.sismultas.fiap.com.br/", "CtbPort"), Ctb.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Ctb
     */
    @WebEndpoint(name = "CtbPort")
    public Ctb getCtbPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.sismultas.fiap.com.br/", "CtbPort"), Ctb.class, features);
    }

}
