
package br.com.fiap.sismultas.mule.car.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "VeiculoWSBean", targetNamespace = "http://ws.sismultas.fiap.com.br/")
public interface VeiculoWSBean {


    /**
     * 
     * @param arg0
     * @return
     *     returns br.com.fiap.sismultas.mule.car.ws.VeiculoVO
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cadastra", targetNamespace = "http://ws.sismultas.fiap.com.br/", className = "br.com.fiap.sismultas.mule.car.ws.Cadastra")
    @ResponseWrapper(localName = "cadastraResponse", targetNamespace = "http://ws.sismultas.fiap.com.br/", className = "br.com.fiap.sismultas.mule.car.ws.CadastraResponse")
    public VeiculoVO cadastra(
        @WebParam(name = "arg0", targetNamespace = "")
        VeiculoVO arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<br.com.fiap.sismultas.mule.car.ws.ModeloVO>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getModelos", targetNamespace = "http://ws.sismultas.fiap.com.br/", className = "br.com.fiap.sismultas.mule.car.ws.GetModelos")
    @ResponseWrapper(localName = "getModelosResponse", targetNamespace = "http://ws.sismultas.fiap.com.br/", className = "br.com.fiap.sismultas.mule.car.ws.GetModelosResponse")
    public List<ModeloVO> getModelos()
        throws Exception_Exception
    ;

}
