
package br.com.fiap.sismultas.init.client;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CargaInicialBean", targetNamespace = "http://init.sismultas.fiap.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CargaInicialBean {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "executaCargaInicial", targetNamespace = "http://init.sismultas.fiap.com.br/", className = "br.com.fiap.sismultas.init.client.ExecutaCargaInicial")
    @ResponseWrapper(localName = "executaCargaInicialResponse", targetNamespace = "http://init.sismultas.fiap.com.br/", className = "br.com.fiap.sismultas.init.client.ExecutaCargaInicialResponse")
    public String executaCargaInicial();

}
