
package br.com.fiap.sismultas.web.ws.consulta;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ConsultaMultas", targetNamespace = "http://ws.sismultas.fiap.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConsultaMultas {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<br.com.fiap.sismultas.web.ws.consulta.InfracaoVO>
     * @throws Exception_Exception
     */
    @WebMethod(action = "consulta")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMultas", targetNamespace = "http://ws.sismultas.fiap.com.br/", className = "br.com.fiap.sismultas.web.ws.consulta.GetMultas")
    @ResponseWrapper(localName = "getMultasResponse", targetNamespace = "http://ws.sismultas.fiap.com.br/", className = "br.com.fiap.sismultas.web.ws.consulta.GetMultasResponse")
    public List<InfracaoVO> getMultas(
        @WebParam(name = "arg0", targetNamespace = "")
        MultaVO arg0)
        throws Exception_Exception
    ;

}
