
package br.com.fiap.sismultas.web.ws.consulta;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ConsultaMultasService", targetNamespace = "http://ws.sismultas.fiap.com.br/", wsdlLocation = "http://localhost:8081/ConsultaMultas?wsdl")
public class ConsultaMultasService
    extends Service
{

    private final static URL CONSULTAMULTASSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.com.fiap.sismultas.web.ws.consulta.ConsultaMultasService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.com.fiap.sismultas.web.ws.consulta.ConsultaMultasService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8081/ConsultaMultas?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8081/ConsultaMultas?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CONSULTAMULTASSERVICE_WSDL_LOCATION = url;
    }

    public ConsultaMultasService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaMultasService() {
        super(CONSULTAMULTASSERVICE_WSDL_LOCATION, new QName("http://ws.sismultas.fiap.com.br/", "ConsultaMultasService"));
    }

    /**
     * 
     * @return
     *     returns ConsultaMultas
     */
    @WebEndpoint(name = "ConsultaMultasPort")
    public ConsultaMultas getConsultaMultasPort() {
        return super.getPort(new QName("http://ws.sismultas.fiap.com.br/", "ConsultaMultasPort"), ConsultaMultas.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaMultas
     */
    @WebEndpoint(name = "ConsultaMultasPort")
    public ConsultaMultas getConsultaMultasPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.sismultas.fiap.com.br/", "ConsultaMultasPort"), ConsultaMultas.class, features);
    }

}
