
package br.com.fiap.sismultas.mule.auth.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AutenticacaoWS", targetNamespace = "http://ws.sismultas.fiap.com.br/", wsdlLocation = "http://localhost:8080/multas-core/AutenticacaoWS/AutenticacaoWSBean?wsdl")
public class AutenticacaoWS
    extends Service
{

    private final static URL AUTENTICACAOWS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.com.fiap.sismultas.mule.auth.ws.AutenticacaoWS.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.com.fiap.sismultas.mule.auth.ws.AutenticacaoWS.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/multas-core/AutenticacaoWS/AutenticacaoWSBean?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/multas-core/AutenticacaoWS/AutenticacaoWSBean?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        AUTENTICACAOWS_WSDL_LOCATION = url;
    }

    public AutenticacaoWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AutenticacaoWS() {
        super(AUTENTICACAOWS_WSDL_LOCATION, new QName("http://ws.sismultas.fiap.com.br/", "AutenticacaoWS"));
    }

    /**
     * 
     * @return
     *     returns AutenticacaoWSBean
     */
    @WebEndpoint(name = "AutenticacaoWSBeanPort")
    public AutenticacaoWSBean getAutenticacaoWSBeanPort() {
        return super.getPort(new QName("http://ws.sismultas.fiap.com.br/", "AutenticacaoWSBeanPort"), AutenticacaoWSBean.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AutenticacaoWSBean
     */
    @WebEndpoint(name = "AutenticacaoWSBeanPort")
    public AutenticacaoWSBean getAutenticacaoWSBeanPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.sismultas.fiap.com.br/", "AutenticacaoWSBeanPort"), AutenticacaoWSBean.class, features);
    }

}
