
package br.com.fiap.sismultas.web.ws.relatorio;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "EmiteRelatorioService", targetNamespace = "http://ws.sismultas.fiap.com.br/", wsdlLocation = "http://localhost:8081/EmiteRelatorio?wsdl")
public class EmiteRelatorioService
    extends Service
{

    private final static URL EMITERELATORIOSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.com.fiap.sismultas.web.ws.relatorio.EmiteRelatorioService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.com.fiap.sismultas.web.ws.relatorio.EmiteRelatorioService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8081/EmiteRelatorio?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8081/EmiteRelatorio?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        EMITERELATORIOSERVICE_WSDL_LOCATION = url;
    }

    public EmiteRelatorioService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmiteRelatorioService() {
        super(EMITERELATORIOSERVICE_WSDL_LOCATION, new QName("http://ws.sismultas.fiap.com.br/", "EmiteRelatorioService"));
    }

    /**
     * 
     * @return
     *     returns EmiteRelatorio
     */
    @WebEndpoint(name = "EmiteRelatorioPort")
    public EmiteRelatorio getEmiteRelatorioPort() {
        return super.getPort(new QName("http://ws.sismultas.fiap.com.br/", "EmiteRelatorioPort"), EmiteRelatorio.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmiteRelatorio
     */
    @WebEndpoint(name = "EmiteRelatorioPort")
    public EmiteRelatorio getEmiteRelatorioPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.sismultas.fiap.com.br/", "EmiteRelatorioPort"), EmiteRelatorio.class, features);
    }

}
