
package br.com.fiap.sismultas.web.ws.relatorio;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "EmiteRelatorio", targetNamespace = "http://ws.sismultas.fiap.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmiteRelatorio {


    /**
     * 
     * @param filtro
     * @return
     *     returns br.com.fiap.sismultas.web.ws.relatorio.RelatorioVO
     * @throws Exception_Exception
     */
    @WebMethod(action = "emiteRelatorio")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "emiteRelatorio", targetNamespace = "http://ws.sismultas.fiap.com.br/", className = "br.com.fiap.sismultas.web.ws.relatorio.EmiteRelatorio_Type")
    @ResponseWrapper(localName = "emiteRelatorioResponse", targetNamespace = "http://ws.sismultas.fiap.com.br/", className = "br.com.fiap.sismultas.web.ws.relatorio.EmiteRelatorioResponse")
    public RelatorioVO emiteRelatorio(
        @WebParam(name = "filtro", targetNamespace = "")
        MultaVO filtro)
        throws Exception_Exception
    ;

}
